services:
  front_dev:
    build:
      context: docker
      dockerfile: Dockerfile.node
      target: dev
    working_dir: /app/svelte-portfolio
    volumes:
      - type: bind
        source: ./svelte-portfolio
        target: /app/svelte-portfolio
    ports:
      # remix
      - "127.0.0.1:5173:5173"
      # vitest
      - "127.0.0.1:51204:51204"
      # ladle
      - "127.0.0.1:61000:61000"
    tty: true

  playwright_vrt:
    build:
      context: docker
      dockerfile: Dockerfile.node
      target: e2e
    working_dir: /app/remix
    volumes:
      - type: bind
        source: ./remix
        target: /app/remix
    ports:
      - 127.0.0.1:9323:9323
