FROM node:20.12.2-slim as base

RUN npm install -g pnpm@9.1.0

# 環境：開発用
FROM base as dev

# エイリアスを設定
COPY ./.alias /root
RUN cat ~/.alias >> ~/.bashrc

WORKDIR /app/frontend


# 環境：e2e用
FROM mcr.microsoft.com/playwright:v1.42.1-jammy as e2e
# バージョン指定は playwright のバージョン依存。合わせる必要あり

COPY --from=base /usr/local/include/ /usr/local/include/
COPY --from=base /usr/local/lib/ /usr/local/lib/
COPY --from=base /usr/local/bin/ /usr/local/bin/
