name: deploy
run-name: deploy to cloudflare

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    defaults:
      run:
        working-directory: remix
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # setup env
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: remix
      # builds
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: portfolio # e.g. 'my-project'
          directory: remix/build/client # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}